### ISSUE TITLE
Create open source JavaScript SDK

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/subscribepro-js#1]
Repo here: https://github.com/subscribepro/subscribepro-js

* Repo should be fully public / open source
* Use the repo for issue tracking, let public submit issues
* Publish the package(s) to npm
* Move over existing API library code and cleanup
* Start versioning at 0.1.0 with semantic versioning

API Coverage:
---

In order to support front-end users who are building My Account / My Subscriptions functions, prioritize API coverage as follows (**DEFINITIVE LIST**):

Catalog:
* GET /services/v2/products
* GET /services/v2/products/{id}
* GET /products
* GET /products/{id}
* POST /services/v2/products
* POST /services/v2/products/{id}
* PATCH /services/v2/products/{id}
* POST /products
* PATCH /product/{id}
* DELETE /product/{id}
* (Bulk and sync products endpoints omitted for now)
* GET /product-configuration-profiles
* GET /product-configuration-profiles/{id}
* GET /scheduling-rules
* GET /scheduling-rules/{id}

Customer Data (customers, addresses, payment profiles, subscriptions):
* GET /services/v2/customers
* GET /services/v2/customers/{id}
* POST /services/v2/customer
* POST /services/v2/customers/{id}
* GET /customers
* GET /customers/{id}
* GET /customers/me
* POST /customers
* PATCH /customers/{id}
* DELETE /customers/{id}
* GET /services/v2/addresses
* GET /services/v2/addresses/{id}
* POST /services/v2/address/find-or-create
* POST /services/v2/address
* POST /services/v2/addresses/{id}
* DELETE /services/v2/addresses/{id}
* GET /customer-addresses
* GET /customer-addresses/{id}
* POST /customer-addresses
* PATCH /customer-addresses/{id}
* DELETE /customer-addresses/{id}
* XXX /services/v2/vault/paymentprofile(s)/*
* XXX /services/v2/subscription(s)/*
* XXX /subscriptions/*

Notes on priority order:
---

* v2 GET subscriptions

Prioritize stuff that currently supports access with customer scoped token and CORS - 

```yaml
  '/services/v1/vault':
      'POST', 'PUT', 'GET'
  '/services/v2/vault':
      'POST', 'PUT', 'GET'
  '/services/v2/products':
      'GET'
  '/services/v2/customer':
      'POST', 'PUT', 'GET'
  '/services/v2/address':
      'POST', 'PUT', 'GET', 'DELETE'
  '/services/v2/subscription':
      'POST', 'PUT', 'GET'
  '/services/v2/config':
      'GET'
```

**Comment by rgarver** [comment]
I'm considering this to be complete. @garthbrantley unless you see any remaining functionality that we've missed or aren't covered by #13, #12, or #11, I think we can close this.
